Refactored SdJwtDoc
lissi-id/sd-jwt-dotnet pull request #9
Opened 2024-05-21 14:01 UTC by ntsbs

This PR improves the parsing of SdJwt via the SdJwtDoc which now returns the secured and unsecured payload of the SdJwt

This PR also removes the deprecated Askar project dependencies, updates the Readme and License information and adds examples for testing.

2024-05-24 07:05 UTC, JoTiTu requested changes

2024-06-10 08:36 UTC, JoTiTu commented
SdJwtVerifierTests and SdJwtDecoder can be removed

2024-06-10 13:58 UTC, JoTiTu approved these changes

2024-06-10 15:06 UTC, ntsbs commented
This PR is closed and recreated with new signed commits

2024-06-10 15:06 UTC, closed without merging